# Generated by Django 6.0.1 on 2026-02-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset_image',
            name='preset_image_url',
            field=models.ImageField(upload_to='account/preset/', verbose_name='アプリ内画像'),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='user_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='account/user/', verbose_name='ユーザーの本体の画像URL'),
        ),
    ]
