# Generated by Django 6.0.1 on 2026-02-09 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='アーティスト名')),
                ('reading_name', models.CharField(max_length=100, verbose_name='読み方')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='会場名')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='会場所在地')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='イベント名')),
                ('live_date', models.DateField(verbose_name='公演日')),
                ('live_image', models.ImageField(blank=True, null=True, upload_to='record/live_image/', verbose_name='参戦記録一覧画面に表示する画像')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
                ('venue_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.venue', verbose_name='会場ID')),
            ],
            options={
                'db_table': 'record',
            },
        ),
        migrations.CreateModel(
            name='Design_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_type', models.CharField(max_length=100, verbose_name='フォントタイプ')),
                ('font_color', models.CharField(max_length=100, verbose_name='フォントの色')),
                ('start_date', models.DateField(verbose_name='表示する参戦記録の開始日')),
                ('end_date', models.DateField(verbose_name='表示する参戦記録の終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('preset_image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.preset_image', verbose_name='アプリ内画像')),
                ('user_image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_image', verbose_name='ユーザー本体の画像')),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.record', verbose_name='参戦記録ID')),
            ],
        ),
        migrations.CreateModel(
            name='Artist_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_links', to='records.artist', verbose_name='アーティストID')),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_records', to='records.record', verbose_name='参戦記録ID')),
            ],
        ),
    ]
