# Generated by Django 6.0.1 on 2026-02-08 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_venue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_record',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_links', to='records.artist', verbose_name='アーティストID'),
        ),
        migrations.AlterField(
            model_name='artist_record',
            name='record_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_records', to='records.record', verbose_name='参戦記録ID'),
        ),
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='record',
            name='live_image',
            field=models.ImageField(blank=True, null=True, upload_to='record/live_image/', verbose_name='参戦記録一覧画面に表示する画像'),
        ),
        migrations.AlterModelTable(
            name='record',
            table='record',
        ),
    ]
